package com.sigo.chat.domain;

public enum SigoTool {
    BUSCAR_TRABAJADOR,
    RESUMEN_ASISTENCIA,
    AUSENCIAS,
    APOYO_SOLICITADO,
    LISTAR_PLAZAS,
    LISTAR_TURNOS,
    LISTAR_MOTIVOS,
    RELEVOS,
    VIAS,
    EVIDENCIAS_ASISTENCIA,
    EVIDENCIAS_RELEVO,
    RESUMEN_GENERAL,
    INCIDENCIAS,
    DESCONOCIDO
}
